### ISSUE TITLE
Method "isSelected" uses String.contains() for its check which leads to bad results

### ISSUE THREAD

**Issue by Aaronmacaron** [cysec-platform/coach-standard-language#8]
## Problem description

At [this line](https://github.com/cysec-platform/coach-standard-language/blob/f34219c65ccf28a245f343815b0bac4d6a2dabcb/src/main/java/eu/smesec/cysec/csl/parser/CommandIsSelected.java#L69) the method "isSelected" checks whether the given parameter is selected. It conducts that check using the Java `String.contains()` method. The problem with that is that for example `isSelected("q8100oHTTPS")` will return true even though the answer with the ID `q8100HTTP` (without an S) is selected. This is the case because HTTP is contained in the HTTPS string.

## Possible solution

The reason for why `String.contains()` is used instead of for example `String.equals()` is because the answer string can contain multiple values when multiple answers are selected on a multiple-choice question. Probably we need a more complex mechanism to make sure that no wrong answers are being selected like described above.

**Comment by simonfreiermuth** [comment]
This issue was resolved in PR #11
